[package]
name = "procmachines"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "State machines in the procedural style"
license = "MIT"
readme = "README.md"
repository = "https://github.com/smallware-io/procmachines"
keywords = ["async", "state-machine", "io", "futures", "protocol"]
categories = ["network-programming", "asynchronous"]

[lib]
name = "procmachines"
path = "src/lib.rs"

[dependencies]
futures = "0.3"
bytes = "1.5"
bytemuck = { version = "1.25", features = ["derive", "extern_crate_alloc"] }
parking_lot = "0.12.5"

[dev-dependencies]
tokio = { version = "1.41", features = ["rt-multi-thread", "macros"] }
